### ISSUE TITLE
Infinitely spawning mobs

### ISSUE THREAD

**Issue by jshaw93** [ExDrill/Cave-Enhancements#13]
Mobs from this mod infinitely spawn surpassing server mob caps in the span of a couple minutes, causing massive issues with spawning other mobs as well as latency issues for servers.

**Comment by ExDrill** [comment]
Minecraft version, mod version and loader?

**Comment by jshaw93** [comment]
1.19.2, 2.1.2, forge

**Comment by ExDrill** [comment]
This has been fixed in later versions, update to 2.1.6 :)
