### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by vizthex123** [ExDrill/Cave-Enhancements#15]
Seems like this mod doesn't properly support it. Disabling it fixes the issue/

Log: 
[latest.log](https://github.com/Team-Abode/Cave-Enhancements/files/10291405/latest.log)

**Comment by ExDrill** [comment]
Cave Enhancements does not have support for 1.19.3, we aren't sure if we want to port it to this version.

**Comment by vizthex123** [comment]
Odd, cuz I use the CuresForge launcher, so it doesn't show mods that aren't supported (unless it's a recent bug). Maybe you guys marked it by accident?

I'd personally like a port though, it seems like a cool mod.

**Comment by vizthex123** [comment]
Yeah, it says right here on the launcher that it supports 1.19.3. Can you uncheck the option on the CF site @ExDrill? Seems others have had this same issue before.
![image](https://user-images.githubusercontent.com/31721920/211670648-963bbe19-9dd3-4437-ae3f-63b860ce2bc2.png)
