### ISSUE TITLE
All of the Block does not play Sound with Presence of the Footstep

### ISSUE THREAD

**Issue by ardissaps** [ExDrill/Cave-Enhancements#2]
Would you fix the material? They does not produce sound when stepped on. Other mods added block (example Blockus) produce sound when stepped with foot.
1.18.2
[Presence of the Foodstep](https://modrinth.com/mod/presence-footsteps)
![image](https://user-images.githubusercontent.com/82106625/175754248-80fee974-1e4c-4552-a506-ac9080a7aeaa.png)

I would like to install again after it fixed, tyvm for the mod.
(Your mod is actually good, but foot sound is big deal for me as it give whole new atmosphere)

**Comment by ExDrill** [comment]
I can fix this for Rose Quartz, but the Goop Block family cannot be fixed, as it uses it's own sounds, thank you for the report.

**Comment by ardissaps** [comment]
> I can fix this for Rose Quartz, but the Goop Block family cannot be fixed, as it uses it's own sounds, thank you for the report.

Alright, I just figured out how to fix them with resource pack with methods provided by them, it is actually not that hard, only need to add lines to blockmap.json. But thanks for the answer!
