### ISSUE TITLE
Crash with the latest fabric api

### ISSUE THREAD

**Issue by masmasmas66** [ExDrill/Cave-Enhancements#6]
[crash-2022-08-16_14.30.01-server.txt](https://github.com/ExDrill/Cave-Enhancements/files/9353524/crash-2022-08-16_14.30.01-server.txt)

**Comment by ExDrill** [comment]
If you revert the fabric api version to 0.58.0, this may be able to solve the issue for the time being.

**Comment by ExDrill** [comment]
Oh wait, nevermind. Yeah Cave Enhancements is not supported for 1.19.2 yet.
